name: NLP2024

logo:
  image: 
  width: 
  height: 
# uncomment the following line to show the site title next to the logo image
site_title: NLP2024
page_title:
  prefix: 'NLP2024: '

calendar:
  colors: #  Colors for the different event hashtags:
    ---: '#bed972'
    qa: '#4FCAEB'
    talk: '#ccc'
  sunday_saturday: false  #  Include Sunday and Saturday
